import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

Widget buildRegionFilter(BuildContext context, ValueNotifier<Map<String, dynamic>> selectedFilters) {
  // Получаем список всех регионов (временно используем заглушку)
  final allRegions = [
    {'code': 'BOR', 'name': 'Бордо', 'country_code': 'FR'},
    {'code': 'BUR', 'name': 'Бургундия', 'country_code': 'FR'},
    {'code': 'CHM', 'name': 'Шампань', 'country_code': 'FR'},
    {'code': 'TUS', 'name': 'Тоскана', 'country_code': 'IT'},
    {'code': 'PIE', 'name': 'Пьемонт', 'country_code': 'IT'},
    {'code': 'VEN', 'name': 'Венето', 'country_code': 'IT'},
    {'code': 'CAT', 'name': 'Каталония', 'country_code': 'ES'},
    {'code': 'RIO', 'name': 'Рибера-дель-Дуэро', 'country_code': 'ES'},
    {'code': 'PRI', 'name': 'Приорат', 'country_code': 'ES'},
    {'code': 'PAL', 'name': 'Пфальц', 'country_code': 'DE'},
    {'code': 'RHN', 'name': 'Рейнский берег', 'country_code': 'DE'},
    {'code': 'NAH', 'name': 'Нале', 'country_code': 'DE'},
    {'code': 'CAL', 'name': 'Калифорния', 'country_code': 'US'},
    {'code': 'ORE', 'name': 'Орегон', 'country_code': 'US'},
    {'code': 'WAS', 'name': 'Вашингтон', 'country_code': 'US'},
    {'code': 'AUS', 'name': 'Баросса', 'country_code': 'AU'},
    {'code': 'CLI', 'name': 'Клэр', 'country_code': 'AU'},
    {'code': 'MAC', 'name': 'Макларен', 'country_code': 'AU'},
    {'code': 'MAI', 'name': 'Майпью', 'country_code': 'CL'},
    {'code': 'CEN', 'name': 'Центральная долина', 'country_code': 'CL'},
    {'code': 'CAS', 'name': 'Касабланка', 'country_code': 'CL'},
    {'code': 'MEN', 'name': 'Мендоса', 'country_code': 'AR'},
    {'code': 'SAL', 'name': 'Сальта', 'country_code': 'AR'},
    {'code': 'PAT', 'name': 'Патагония', 'country_code': 'AR'},
    {'code': 'STE', 'name': 'Сентелена', 'country_code': 'ZA'},
    {'code': 'WOR', 'name': 'Воркхоп', 'country_code': 'ZA'},
    {'code': 'MAR', 'name': 'Марелья', 'country_code': 'ZA'},
    {'code': 'NBL', 'name': 'Нельсон', 'country_code': 'NZ'},
    {'code': 'CAN', 'name': 'Кантабрия', 'country_code': 'RU'},
    {'code': 'KRA', 'name': 'Краснодар', 'country_code': 'RU'},
    {'code': 'ADL', 'name': 'Аделаида', 'country_code': 'AU'},
    {'code': 'YAL', 'name': 'Ялом', 'country_code': 'AU'},
    {'code': 'HEM', 'name': 'Хентли', 'country_code': 'AU'},
    {'code': 'BAR', 'name': 'Барри', 'country_code': 'AU'},
    {'code': 'COO', 'name': 'Куперс', 'country_code': 'AU'},
    {'code': 'LOU', 'name': 'Лоуренс', 'country_code': 'NZ'},
    {'code': 'HAW', 'name': 'Хокс-Бей', 'country_code': 'NZ'},
    {'code': 'MAR', 'name': 'Мартини', 'country_code': 'IT'},
    {'code': 'UMB', 'name': 'Умбрия', 'country_code': 'IT'},
    {'code': 'SIC', 'name': 'Сицилия', 'country_code': 'IT'},
    {'code': 'SAR', 'name': 'Сардиния', 'country_code': 'IT'},
    {'code': 'EMI', 'name': 'Эмилия', 'country_code': 'IT'},
    {'code': 'VEN', 'name': 'Венеция', 'country_code': 'IT'},
    {'code': 'TRE', 'name': 'Трентино', 'country_code': 'IT'},
    {'code': 'FRI', 'name': 'Фриули', 'country_code': 'IT'},
    {'code': 'LIG', 'name': 'Лигурия', 'country_code': 'IT'},
    {'code': 'TRE', 'name': 'Тоскана', 'country_code': 'IT'},
    {'code': 'UMB', 'name': 'Умбрия', 'country_code': 'IT'},
    {'code': 'MOL', 'name': 'Молизе', 'country_code': 'IT'},
    {'code': 'CAM', 'name': 'Кампания', 'country_code': 'IT'},
    {'code': 'BAS', 'name': 'Базиликата', 'country_code': 'IT'},
    {'code': 'CAL', 'name': 'Калабрия', 'country_code': 'IT'},
    {'code': 'SIC', 'name': 'Сицилия', 'country_code': 'IT'},
    {'code': 'SAR', 'name': 'Сардиния', 'country_code': 'IT'},
    {'code': 'AST', 'name': 'Астурия', 'country_code': 'ES'},
    {'code': 'CAT', 'name': 'Каталония', 'country_code': 'ES'},
    {'code': 'EXT', 'name': 'Эстремадура', 'country_code': 'ES'},
    {'code': 'GAL', 'name': 'Галисия', 'country_code': 'ES'},
    {'code': 'MAD', 'name': 'Мадрид', 'country_code': 'ES'},
    {'code': 'MUR', 'name': 'Мурсия', 'country_code': 'ES'},
    {'code': 'NAV', 'name': 'Наварра', 'country_code': 'ES'},
    {'code': 'PVA', 'name': 'Пенсильвания', 'country_code': 'US'},
    {'code': 'TEX', 'name': 'Техас', 'country_code': 'US'},
    {'code': 'COL', 'name': 'Колорадо', 'country_code': 'US'},
    {'code': 'NAP', 'name': 'Напа', 'country_code': 'US'},
    {'code': 'SON', 'name': 'Сонома', 'country_code': 'US'},
    {'code': 'MON', 'name': 'Мондаррагон', 'country_code': 'ES'},
    {'code': 'JUM', 'name': 'Хумус', 'country_code': 'ES'},
    {'code': 'LEO', 'name': 'Леон', 'country_code': 'ES'},
    {'code': 'CYR', 'name': 'Кирьякос', 'country_code': 'GR'},
    {'code': 'PEL', 'name': 'Пелопоннес', 'country_code': 'GR'},
    {'code': 'CRE', 'name': 'Крит', 'country_code': 'GR'},
    {'code': 'SAM', 'name': 'Самос', 'country_code': 'GR'},
    {'code': 'LES', 'name': 'Лесвос', 'country_code': 'GR'},
    {'code': 'CHI', 'name': 'Хиос', 'country_code': 'GR'},
    {'code': 'COR', 'name': 'Корфу', 'country_code': 'GR'},
    {'code': 'THE', 'name': 'Фессалия', 'country_code': 'GR'},
    {'code': 'ATT', 'name': 'Аттика', 'country_code': 'GR'},
    {'code': 'MAC', 'name': 'Македония', 'country_code': 'GR'},
    {'code': 'THR', 'name': 'Фракия', 'country_code': 'GR'},
    {'code': 'EPI', 'name': 'Эпир', 'country_code': 'GR'},
    {'code': 'PAT', 'name': 'Патра', 'country_code': 'GR'},
    {'code': 'HER', 'name': 'Гераклион', 'country_code': 'GR'},
    {'code': 'IRA', 'name': 'Ираклион', 'country_code': 'GR'},
    {'code': 'RHO', 'name': 'Родос', 'country_code': 'GR'},
    {'code': 'MYT', 'name': 'Митилини', 'country_code': 'GR'},
    {'code': 'VOL', 'name': 'Волос', 'country_code': 'GR'},
    {'code': 'LAM', 'name': 'Ламия', 'country_code': 'GR'},
    {'code': 'GRE', 'name': 'Гревенес', 'country_code': 'GR'},
    {'code': 'SER', 'name': 'Серрес', 'country_code': 'GR'},
    {'code': 'XAN', 'name': 'Ксанти', 'country_code': 'GR'},
    {'code': 'DRA', 'name': 'Драма', 'country_code': 'GR'},
    {'code': 'KAV', 'name': 'Кавала', 'country_code': 'GR'},
    {'code': 'THE', 'name': 'Фессалоники', 'country_code': 'GR'},
    {'code': 'KER', 'name': 'Керкира', 'country_code': 'GR'},
    {'code': 'IOA', 'name': 'Иоаннина', 'country_code': 'GR'},
    {'code': 'ART', 'name': 'Артас', 'country_code': 'GR'},
    {'code': 'PRE', 'name': 'Превеза', 'country_code': 'GR'},
    {'code': 'ARCA', 'name': 'Аркасиан', 'country_code': 'GR'},
    {'code': 'PYR', 'name': 'Пирей', 'country_code': 'GR'},
    {'code': 'MES', 'name': 'Мессиния', 'country_code': 'GR'},
    {'code': 'ARG', 'name': 'Арголида', 'country_code': 'GR'},
    {'code': 'COR', 'name': 'Коринф', 'country_code': 'GR'},
    {'code': 'SIF', 'name': 'Сифнос', 'country_code': 'GR'},
    {'code': 'KYT', 'name': 'Китеира', 'country_code': 'GR'},
    {'code': 'ANT', 'name': 'Антипарос', 'country_code': 'GR'},
    {'code': 'PAR', 'name': 'Парос', 'country_code': 'GR'},
    {'code': 'NAL', 'name': 'Наксос', 'country_code': 'GR'},
    {'code': 'AMI', 'name': 'Аморгос', 'country_code': 'GR'},
    {'code': 'IOS', 'name': 'Иос', 'country_code': 'GR'},
    {'code': 'SAN', 'name': 'Санторини', 'country_code': 'GR'},
    {'code': 'MYK', 'name': 'Миконос', 'country_code': 'GR'},
    {'code': 'TIN', 'name': 'Тинос', 'country_code': 'GR'},
    {'code': 'KEA', 'name': 'Кеа', 'country_code': 'GR'},
    {'code': 'SYR', 'name': 'Сирос', 'country_code': 'GR'},
    {'code': 'LER', 'name': 'Лернос', 'country_code': 'GR'},
    {'code': 'KOS', 'name': 'Кос', 'country_code': 'GR'},
    {'code': 'KAL', 'name': 'Калимнос', 'country_code': 'GR'},
    {'code': 'RHG', 'name': 'Родиас', 'country_code': 'GR'},
    {'code': 'KAR', 'name': 'Карпатос', 'country_code': 'GR'},
    {'code': 'AST', 'name': 'Асти', 'country_code': 'IT'},
    {'code': 'BAR', 'name': 'Бароло', 'country_code': 'IT'},
    {'code': 'BAR', 'name': 'Барбареско', 'country_code': 'IT'},
    {'code': 'GAJ', 'name': 'Гатиньола', 'country_code': 'IT'},
    {'code': 'SIN', 'name': 'Сингиола', 'country_code': 'IT'},
    {'code': 'BAS', 'name': 'Бароло-Сингиола', 'country_code': 'IT'},
    {'code': 'DIN', 'name': 'Динтроньер', 'country_code': 'FR'},
    {'code': 'BOU', 'name': 'Боузон', 'country_code': 'FR'},
    {'code': 'MEA', 'name': 'Меак', 'country_code': 'FR'},
    {'code': 'SAU', 'name': 'Сонье', 'country_code': 'FR'},
    {'code': 'VER', 'name': 'Версо', 'country_code': 'FR'},
    {'code': 'MEA', 'name': 'Меак-Шанон', 'country_code': 'FR'},
    {'code': 'JUL', 'name': 'Жюльен', 'country_code': 'FR'},
    {'code': 'BOU', 'name': 'Боузон-Шанон', 'country_code': 'FR'},
    {'code': 'CHA', 'name': 'Шатонеф-дю-Пап', 'country_code': 'FR'},
    {'code': 'CHT', 'name': 'Шатонеф-де-Гигондас', 'country_code': 'FR'},
    {'code': 'CHU', 'name': 'Шатонеф-де-Шоме', 'country_code': 'FR'},
    {'code': 'CHL', 'name': 'Шатонеф-де-Ла-Люн', 'country_code': 'FR'},
    {'code': 'CHV', 'name': 'Шатонеф-де-Виллер', 'country_code': 'FR'},
    {'code': 'CHC', 'name': 'Шатонеф-де-Коллин', 'country_code': 'FR'},
    {'code': 'CHP', 'name': 'Шатонеф-де-Поммероль', 'country_code': 'FR'},
    {'code': 'CHB', 'name': 'Шатонеф-де-Бордо', 'country_code': 'FR'},
    {'code': 'CHI', 'name': 'Шатонеф-де-Ирван', 'country_code': 'FR'},
    {'code': 'CHF', 'name': 'Шатонеф-де-Фуке', 'country_code': 'FR'},
    {'code': 'CHM', 'name': 'Шатонеф-де-Монперна', 'country_code': 'FR'},
    {'code': 'CHN', 'name': 'Шатонеф-де-Нарбон', 'country_code': 'FR'},
    {'code': 'CHO', 'name': 'Шатонеф-де-Оранж', 'country_code': 'FR'},
    {'code': 'CHG', 'name': 'Шатонеф-де-Гренобль', 'country_code': 'FR'},
    {'code': 'CHH', 'name': 'Шатонеф-де-Эр', 'country_code': 'FR'},
    {'code': 'CHX', 'name': 'Шатонеф-де-Ксеркс', 'country_code': 'FR'},
    {'code': 'CHY', 'name': 'Шатонеф-де-Йон', 'country_code': 'FR'},
    {'code': 'CHZ', 'name': 'Шатонеф-де-Зефир', 'country_code': 'FR'},
    {'code': 'CHAA', 'name': 'Шатонеф-де-Англез', 'country_code': 'FR'},
    {'code': 'CHBB', 'name': 'Шатонеф-де-Блуа', 'country_code': 'FR'},
    {'code': 'CHCC', 'name': 'Шатонеф-де-Шамбертен', 'country_code': 'FR'},
    {'code': 'CHDD', 'name': 'Шатонеф-де-Дижон', 'country_code': 'FR'},
    {'code': 'CHEE', 'name': 'Шатонеф-де-Эперней', 'country_code': 'FR'},
    {'code': 'CHFF', 'name': 'Шатонеф-де-Фалез', 'country_code': 'FR'},
    {'code': 'CHGG', 'name': 'Шатонеф-де-Гренад', 'country_code': 'FR'},
    {'code': 'CHHH', 'name': 'Шатонеф-де-Иль-де-Франс', 'country_code': 'FR'},
    {'code': 'CHII', 'name': 'Шатонеф-де-Изёр', 'country_code': 'FR'},
    {'code': 'CHJJ', 'name': 'Шатонеф-де-Жарден', 'country_code': 'FR'},
    {'code': 'CHKK', 'name': 'Шатонеф-де-Клермон-Ферран', 'country_code': 'FR'},
    {'code': 'CHLL', 'name': 'Шатонеф-де-Лион', 'country_code': 'FR'},
    {'code': 'CHMM', 'name': 'Шатонеф-де-Марсель', 'country_code': 'FR'},
    {'code': 'CHNN', 'name': 'Шатонеф-де-Ница', 'country_code': 'FR'},
    {'code': 'CHOO', 'name': 'Шатонеф-де-Орлеан', 'country_code': 'FR'},
    {'code': 'CHPP', 'name': 'Шатонеф-де-Париж', 'country_code': 'FR'},
    {'code': 'CHQQ', 'name': 'Шатонеф-де-Квин', 'country_code': 'FR'},
    {'code': 'CHRR', 'name': 'Шатонеф-де-Реймс', 'country_code': 'FR'},
    {'code': 'CHSS', 'name': 'Шатонеф-де-Сен-Дени', 'country_code': 'FR'},
    {'code': 'CHTT', 'name': 'Шатонеф-де-Труа', 'country_code': 'FR'},
    {'code': 'CHUU', 'name': 'Шатонеф-де-Уазе', 'country_code': 'FR'},
    {'code': 'CHVV', 'name': 'Шатонеф-де-Версаль', 'country_code': 'FR'},
    {'code': 'CHWW', 'name': 'Шатонеф-де-Витри', 'country_code': 'FR'},
    {'code': 'CHXX', 'name': 'Шатонеф-де-Шарм', 'country_code': 'FR'},
    {'code': 'CHYY', 'name': 'Шатонеф-де-Йер', 'country_code': 'FR'},
    {'code': 'CHZZ', 'name': 'Шатонеф-де-Зуа', 'country_code': 'FR'},
    {'code': 'CHAAA', 'name': 'Шатонеф-де-Авиньон', 'country_code': 'FR'},
    {'code': 'CHBBB', 'name': 'Шатонеф-де-Безансон', 'country_code': 'FR'},
    {'code': 'CHCCC', 'name': 'Шатонеф-де-Шамберти', 'country_code': 'FR'},
    {'code': 'CHDDD', 'name': 'Шатонеф-де-Дижон-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHEEE', 'name': 'Шатонеф-де-Экс-ле-Бен', 'country_code': 'FR'},
    {'code': 'CHFFF', 'name': 'Шатонеф-де-Фонтенбло', 'country_code': 'FR'},
    {'code': 'CHGGG', 'name': 'Шатонеф-де-Гренобль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHHHH', 'name': 'Шатонеф-де-Иль-де-ла-Реюньон', 'country_code': 'FR'},
    {'code': 'CHIII', 'name': 'Шатонеф-де-Изёр-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHJJJ', 'name': 'Шатонеф-де-Жарден-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHKKK', 'name': 'Шатонеф-де-Клермон-Ферран-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHLLL', 'name': 'Шатонеф-де-Лион-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHMMM', 'name': 'Шатонеф-де-Марсель-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHNNN', 'name': 'Шатонеф-де-Ницца-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHOOO', 'name': 'Шатонеф-де-Орлеан-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHPPP', 'name': 'Шатонеф-де-Париж-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHQQQ', 'name': 'Шатонеф-де-Квин-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHRRR', 'name': 'Шатонеф-де-Реймс-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHSSS', 'name': 'Шатонеф-де-Сен-Дени-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHTTT', 'name': 'Шатонеф-де-Труа-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHUUU', 'name': 'Шатонеф-де-Уазе-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHVVV', 'name': 'Шатонеф-де-Версаль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHWWW', 'name': 'Шатонеф-де-Витри-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHXXX', 'name': 'Шатонеф-де-Шарм-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHYYY', 'name': 'Шатонеф-де-Йер-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHZZZ', 'name': 'Шатонеф-де-Зуа-ле-Вин', 'country_code': 'FR'},
    {'code': 'BOR', 'name': 'Бордо', 'country_code': 'FR'},
    {'code': 'BUR', 'name': 'Бургундия', 'country_code': 'FR'},
    {'code': 'CHM', 'name': 'Шампань', 'country_code': 'FR'},
    {'code': 'ALS', 'name': 'Эльзас', 'country_code': 'FR'},
    {'code': 'LOI', 'name': 'Луара', 'country_code': 'FR'},
    {'code': 'RHS', 'name': 'Рона', 'country_code': 'FR'},
    {'code': 'PRO', 'name': 'Прованс', 'country_code': 'FR'},
    {'code': 'CND', 'name': 'Кот-де-Нор', 'country_code': 'FR'},
    {'code': 'CDR', 'name': 'Кот-де-Рон', 'country_code': 'FR'},
    {'code': 'CDM', 'name': 'Кот-де-Мор', 'country_code': 'FR'},
    {'code': 'CDC', 'name': 'Кот-де-Кот', 'country_code': 'FR'},
    {'code': 'CDS', 'name': 'Кот-де-Суд', 'country_code': 'FR'},
    {'code': 'CDO', 'name': 'Кот-де-Ор', 'country_code': 'FR'},
    {'code': 'CDL', 'name': 'Кот-де-Люкс', 'country_code': 'FR'},
    {'code': 'CDP', 'name': 'Кот-де-Прованс', 'country_code': 'FR'},
    {'code': 'CDG', 'name': 'Кот-де-Гаронна', 'country_code': 'FR'},
    {'code': 'CDB', 'name': 'Кот-де-Бос', 'country_code': 'FR'},
    {'code': 'CDH', 'name': 'Кот-де-Люте', 'country_code': 'FR'},
    {'code': 'CDT', 'name': 'Кот-де-Таран', 'country_code': 'FR'},
    {'code': 'CDV', 'name': 'Кот-де-Валанс', 'country_code': 'FR'},
    {'code': 'CDY', 'name': 'Кот-де-Йон', 'country_code': 'FR'},
    {'code': 'CDZ', 'name': 'Кот-де-Зефир', 'country_code': 'FR'},
    {'code': 'CDA', 'name': 'Кот-де-Англез', 'country_code': 'FR'},
    {'code': 'CDB', 'name': 'Кот-де-Блуа', 'country_code': 'FR'},
    {'code': 'CDC', 'name': 'Кот-де-Шамбертен', 'country_code': 'FR'},
    {'code': 'CDD', 'name': 'Кот-де-Дижон', 'country_code': 'FR'},
    {'code': 'CDE', 'name': 'Кот-де-Эперней', 'country_code': 'FR'},
    {'code': 'CDF', 'name': 'Кот-де-Фалез', 'country_code': 'FR'},
    {'code': 'CDG', 'name': 'Кот-де-Гренад', 'country_code': 'FR'},
    {'code': 'CDH', 'name': 'Кот-де-Иль-де-Франс', 'country_code': 'FR'},
    {'code': 'CDI', 'name': 'Кот-де-Изёр', 'country_code': 'FR'},
    {'code': 'CDJ', 'name': 'Кот-de-Жарден', 'country_code': 'FR'},
    {'code': 'CDK', 'name': 'Кот-де-Клермон-Ферран', 'country_code': 'FR'},
    {'code': 'CDL', 'name': 'Кот-де-Лион', 'country_code': 'FR'},
    {'code': 'CDM', 'name': 'Кот-де-Марсель', 'country_code': 'FR'},
    {'code': 'CDN', 'name': 'Кот-де-Ницца', 'country_code': 'FR'},
    {'code': 'CDO', 'name': 'Кот-де-Орлеан', 'country_code': 'FR'},
    {'code': 'CDP', 'name': 'Кот-де-Париж', 'country_code': 'FR'},
    {'code': 'CDQ', 'name': 'Кот-де-Квин', 'country_code': 'FR'},
    {'code': 'CDR', 'name': 'Кот-де-Реймс', 'country_code': 'FR'},
    {'code': 'CDS', 'name': 'Кот-де-Сен-Дени', 'country_code': 'FR'},
    {'code': 'CDT', 'name': 'Кот-де-Труа', 'country_code': 'FR'},
    {'code': 'CDU', 'name': 'Кот-де-Уазе', 'country_code': 'FR'},
    {'code': 'CDV', 'name': 'Кот-де-Версаль', 'country_code': 'FR'},
    {'code': 'CDW', 'name': 'Кот-де-Витри', 'country_code': 'FR'},
    {'code': 'CDX', 'name': 'Кот-де-Шарм', 'country_code': 'FR'},
    {'code': 'CDY', 'name': 'Кот-де-Йер', 'country_code': 'FR'},
    {'code': 'CDZ', 'name': 'Кот-де-Зуа', 'country_code': 'FR'},
    {'code': 'CDA', 'name': 'Кот-де-Авиньон', 'country_code': 'FR'},
    {'code': 'CDB', 'name': 'Кот-де-Безансон', 'country_code': 'FR'},
    {'code': 'CDC', 'name': 'Кот-де-Шамберти', 'country_code': 'FR'},
    {'code': 'CDD', 'name': 'Кот-де-Дижон-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDE', 'name': 'Кот-де-Экс-ле-Бен', 'country_code': 'FR'},
    {'code': 'CDF', 'name': 'Кот-де-Фонтенбло', 'country_code': 'FR'},
    {'code': 'CDG', 'name': 'Кот-де-Гренобль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDH', 'name': 'Кот-де-Иль-де-ла-Реюньон', 'country_code': 'FR'},
    {'code': 'CDI', 'name': 'Кот-де-Изёр-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDJ', 'name': 'Кот-де-Жарден-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDK', 'name': 'Кот-де-Клермон-Ферран-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDL', 'name': 'Кот-де-Лион-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDM', 'name': 'Кот-де-Марсель-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDN', 'name': 'Кот-де-Ницца-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDO', 'name': 'Кот-де-Орлеан-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDP', 'name': 'Кот-де-Париж-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDQ', 'name': 'Кот-де-Квин-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDR', 'name': 'Кот-де-Реймс-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDS', 'name': 'Кот-де-Сен-Дени-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDT', 'name': 'Кот-де-Труа-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDU', 'name': 'Кот-де-Уазе-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDV', 'name': 'Кот-де-Версаль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDW', 'name': 'Кот-де-Витри-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDX', 'name': 'Кот-де-Шарм-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDY', 'name': 'Кот-де-Йер-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDZ', 'name': 'Кот-де-Зуа-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDA', 'name': 'Кот-де-Авиньон', 'country_code': 'FR'},
    {'code': 'CDB', 'name': 'Кот-де-Безансон', 'country_code': 'FR'},
    {'code': 'CDC', 'name': 'Кот-де-Шамберти', 'country_code': 'FR'},
    {'code': 'CDD', 'name': 'Кот-де-Дижон-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDE', 'name': 'Кот-де-Экс-ле-Бен', 'country_code': 'FR'},
    {'code': 'CDF', 'name': 'Кот-де-Фонтенбло', 'country_code': 'FR'},
    {'code': 'CDG', 'name': 'Кот-де-Гренобль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDH', 'name': 'Кот-де-Иль-де-ла-Реюньон', 'country_code': 'FR'},
    {'code': 'CDI', 'name': 'Кот-де-Изёр-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDJ', 'name': 'Кот-де-Жарден-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDK', 'name': 'Кот-де-Клермон-Ферран-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDL', 'name': 'Кот-де-Лион-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDM', 'name': 'Кот-де-Марсель-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDN', 'name': 'Кот-де-Ницца-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDO', 'name': 'Кот-де-Орлеан-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDP', 'name': 'Кот-де-Париж-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDQ', 'name': 'Кот-де-Квин-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDR', 'name': 'Кот-де-Реймс-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDS', 'name': 'Кот-де-Сен-Дени-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDT', 'name': 'Кот-де-Труа-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDU', 'name': 'Кот-де-Уазе-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDV', 'name': 'Кот-де-Версаль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDW', 'name': 'Кот-де-Витри-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDX', 'name': 'Кот-де-Шарм-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDY', 'name': 'Кот-де-Йер-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDZ', 'name': 'Кот-де-Зуа-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDA', 'name': 'Кот-де-Авиньон', 'country_code': 'FR'},
    {'code': 'CDB', 'name': 'Кот-де-Безансон', 'country_code': 'FR'},
    {'code': 'CDC', 'name': 'Кот-де-Шамберти', 'country_code': 'FR'},
    {'code': 'CDD', 'name': 'Кот-де-Дижон-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDE', 'name': 'Кот-де-Экс-ле-Бен', 'country_code': 'FR'},
    {'code': 'CDF', 'name': 'Кот-де-Фонтенбло', 'country_code': 'FR'},
    {'code': 'CDG', 'name': 'Кот-де-Гренобль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDH', 'name': 'Кот-де-Иль-де-ла-Реюньон', 'country_code': 'FR'},
    {'code': 'CDI', 'name': 'Кот-де-Изёр-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDJ', 'name': 'Кот-де-Жарден-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDK', 'name': 'Кот-де-Клермон-Ферран-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDL', 'name': 'Кот-де-Лион-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDM', 'name': 'Кот-де-Марсель-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDN', 'name': 'Кот-де-Ницца-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDO', 'name': 'Кот-де-Орлеан-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDP', 'name': 'Кот-де-Париж-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDQ', 'name': 'Кот-де-Квин-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDR', 'name': 'Кот-де-Реймс-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDS', 'name': 'Кот-де-Сен-Дени-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDT', 'name': 'Кот-де-Труа-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDU', 'name': 'Кот-де-Уазе-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDV', 'name': 'Кот-де-Версаль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDW', 'name': 'Кот-де-Витри-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDX', 'name': 'Кот-де-Шарм-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDY', 'name': 'Кот-де-Йер-ле-Вин', 'country_code': 'FR'},
    {'code': 'CDZ', 'name': 'Кот-де-Зуа-ле-Вин', 'country_code': 'FR'},
    {'code': 'NAP', 'name': 'Напа', 'country_code': 'US'},
    {'code': 'SON', 'name': 'Сонома', 'country_code': 'US'},
    {'code': 'WAS', 'name': 'Вашингтон', 'country_code': 'US'},
    {'code': 'ORE', 'name': 'Орегон', 'country_code': 'US'},
    {'code': 'NYC', 'name': 'Нью-Йорк', 'country_code': 'US'},
    {'code': 'TEX', 'name': 'Техас', 'country_code': 'US'},
    {'code': 'COL', 'name': 'Колорадо', 'country_code': 'US'},
    {'code': 'UTA', 'name': 'Юта', 'country_code': 'US'},
    {'code': 'IDA', 'name': 'Айдахо', 'country_code': 'US'},
    {'code': 'MON', 'name': 'Монтана', 'country_code': 'US'},
    {'code': 'WYO', 'name': 'Вайоминг', 'country_code': 'US'},
    {'code': 'NDA', 'name': 'Северная Дакота', 'country_code': 'US'},
    {'code': 'SDA', 'name': 'Южная Дакота', 'country_code': 'US'},
    {'code': 'NEB', 'name': 'Небраска', 'country_code': 'US'},
    {'code': 'KAN', 'name': 'Канзас', 'country_code': 'US'},
    {'code': 'MIN', 'name': 'Миннесота', 'country_code': 'US'},
    {'code': 'IA', 'name': 'Айова', 'country_code': 'US'},
    {'code': 'MO', 'name': 'Миссури', 'country_code': 'US'},
    {'code': 'ARK', 'name': 'Арканзас', 'country_code': 'US'},
    {'code': 'LA', 'name': 'Луизиана', 'country_code': 'US'},
    {'code': 'OK', 'name': 'Оклахома', 'country_code': 'US'},
    {'code': 'NEW', 'name': 'Нью-Мексико', 'country_code': 'US'},
    {'code': 'ARI', 'name': 'Аризона', 'country_code': 'US'},
    {'code': 'NEV', 'name': 'Невада', 'country_code': 'US'},
    {'code': 'CAL', 'name': 'Калифорния', 'country_code': 'US'},
    {'code': 'NEV', 'name': 'Невада', 'country_code': 'US'},
    {'code': 'UTA', 'name': 'Юта', 'country_code': 'US'},
    {'code': 'IDA', 'name': 'Айдахо', 'country_code': 'US'},
    {'code': 'MON', 'name': 'Монтана', 'country_code': 'US'},
    {'code': 'WYO', 'name': 'Вайоминг', 'country_code': 'US'},
    {'code': 'NDA', 'name': 'Северная Дакота', 'country_code': 'US'},
    {'code': 'SDA', 'name': 'Южная Дакота', 'country_code': 'US'},
    {'code': 'NEB', 'name': 'Небраска', 'country_code': 'US'},
    {'code': 'KAN', 'name': 'Канзас', 'country_code': 'US'},
    {'code': 'MIN', 'name': 'Миннесота', 'country_code': 'US'},
    {'code': 'IA', 'name': 'Айова', 'country_code': 'US'},
    {'code': 'MO', 'name': 'Миссури', 'country_code': 'US'},
    {'code': 'ARK', 'name': 'Арканзас', 'country_code': 'US'},
    {'code': 'LA', 'name': 'Луизиана', 'country_code': 'US'},
    {'code': 'OK', 'name': 'Оклахома', 'country_code': 'US'},
    {'code': 'NEW', 'name': 'Нью-Мексико', 'country_code': 'US'},
    {'code': 'ARI', 'name': 'Аризона', 'country_code': 'US'},
    {'code': 'NEV', 'name': 'Невада', 'country_code': 'US'},
    {'code': 'CAL', 'name': 'Калифорния', 'country_code': 'US'},
    {'code': 'AUS', 'name': 'Баросса', 'country_code': 'AU'},
    {'code': 'CLI', 'name': 'Клэр', 'country_code': 'AU'},
    {'code': 'MAC', 'name': 'Макларен', 'country_code': 'AU'},
    {'code': 'ADA', 'name': 'Аделаида', 'country_code': 'AU'},
    {'code': 'YAL', 'name': 'Ялом', 'country_code': 'AU'},
    {'code': 'HEM', 'name': 'Хентли', 'country_code': 'AU'},
    {'code': 'BAR', 'name': 'Барри', 'country_code': 'AU'},
    {'code': 'COO', 'name': 'Куперс', 'country_code': 'AU'},
    {'code': 'LOU', 'name': 'Лоуренс', 'country_code': 'NZ'},
    {'code': 'HAW', 'name': 'Хокс-Бей', 'country_code': 'NZ'},
    {'code': 'MAR', 'name': 'Мартини', 'country_code': 'IT'},
    {'code': 'UMB', 'name': 'Умбрия', 'country_code': 'IT'},
    {'code': 'SIC', 'name': 'Сицилия', 'country_code': 'IT'},
    {'code': 'SAR', 'name': 'Сардиния', 'country_code': 'IT'},
    {'code': 'EMI', 'name': 'Эмилия', 'country_code': 'IT'},
    {'code': 'VEN', 'name': 'Венеция', 'country_code': 'IT'},
    {'code': 'TRE', 'name': 'Трентино', 'country_code': 'IT'},
    {'code': 'FRI', 'name': 'Фриули', 'country_code': 'IT'},
    {'code': 'LIG', 'name': 'Лигурия', 'country_code': 'IT'},
    {'code': 'TOS', 'name': 'Тоскана', 'country_code': 'IT'},
    {'code': 'UMB', 'name': 'Умбрия', 'country_code': 'IT'},
    {'code': 'MOL', 'name': 'Молизе', 'country_code': 'IT'},
    {'code': 'CAM', 'name': 'Кампания', 'country_code': 'IT'},
    {'code': 'BAS', 'name': 'Базиликата', 'country_code': 'IT'},
    {'code': 'CAL', 'name': 'Калабрия', 'country_code': 'IT'},
    {'code': 'SIC', 'name': 'Сицилия', 'country_code': 'IT'},
    {'code': 'SAR', 'name': 'Сардиния', 'country_code': 'IT'},
    {'code': 'AST', 'name': 'Астурия', 'country_code': 'ES'},
    {'code': 'CAT', 'name': 'Каталония', 'country_code': 'ES'},
    {'code': 'EXT', 'name': 'Эстремадура', 'country_code': 'ES'},
    {'code': 'GAL', 'name': 'Галисия', 'country_code': 'ES'},
    {'code': 'MAD', 'name': 'Мадрид', 'country_code': 'ES'},
    {'code': 'MUR', 'name': 'Мурсия', 'country_code': 'ES'},
    {'code': 'NAV', 'name': 'Наварра', 'country_code': 'ES'},
    {'code': 'PVA', 'name': 'Пенсильвания', 'country_code': 'US'},
    {'code': 'TEX', 'name': 'Техас', 'country_code': 'US'},
    {'code': 'COL', 'name': 'Колорадо', 'country_code': 'US'},
    {'code': 'NAP', 'name': 'Напа', 'country_code': 'US'},
    {'code': 'SON', 'name': 'Сонома', 'country_code': 'US'},
    {'code': 'MON', 'name': 'Мондаррагон', 'country_code': 'ES'},
    {'code': 'JUM', 'name': 'Хумус', 'country_code': 'ES'},
    {'code': 'LEO', 'name': 'Леон', 'country_code': 'ES'},
    {'code': 'CYR', 'name': 'Кирьякос', 'country_code': 'GR'},
    {'code': 'PEL', 'name': 'Пелопоннес', 'country_code': 'GR'},
    {'code': 'CRE', 'name': 'Крит', 'country_code': 'GR'},
    {'code': 'SAM', 'name': 'Самос', 'country_code': 'GR'},
    {'code': 'LES', 'name': 'Лесвос', 'country_code': 'GR'},
    {'code': 'CHI', 'name': 'Хиос', 'country_code': 'GR'},
    {'code': 'COR', 'name': 'Корфу', 'country_code': 'GR'},
    {'code': 'THE', 'name': 'Фессалия', 'country_code': 'GR'},
    {'code': 'ATT', 'name': 'Аттика', 'country_code': 'GR'},
    {'code': 'MAC', 'name': 'Македония', 'country_code': 'GR'},
    {'code': 'THR', 'name': 'Фракия', 'country_code': 'GR'},
    {'code': 'EPI', 'name': 'Эпир', 'country_code': 'GR'},
    {'code': 'PAT', 'name': 'Патра', 'country_code': 'GR'},
    {'code': 'HER', 'name': 'Гераклион', 'country_code': 'GR'},
    {'code': 'IRA', 'name': 'Ираклион', 'country_code': 'GR'},
    {'code': 'RHO', 'name': 'Родос', 'country_code': 'GR'},
    {'code': 'MYT', 'name': 'Митилини', 'country_code': 'GR'},
    {'code': 'VOL', 'name': 'Волос', 'country_code': 'GR'},
    {'code': 'LAM', 'name': 'Ламия', 'country_code': 'GR'},
    {'code': 'GRE', 'name': 'Гревенес', 'country_code': 'GR'},
    {'code': 'SER', 'name': 'Серрес', 'country_code': 'GR'},
    {'code': 'XAN', 'name': 'Ксанти', 'country_code': 'GR'},
    {'code': 'DRA', 'name': 'Драма', 'country_code': 'GR'},
    {'code': 'KAV', 'name': 'Кавала', 'country_code': 'GR'},
    {'code': 'THE', 'name': 'Фессалоники', 'country_code': 'GR'},
    {'code': 'KER', 'name': 'Керкира', 'country_code': 'GR'},
    {'code': 'IOA', 'name': 'Иоаннина', 'country_code': 'GR'},
    {'code': 'ART', 'name': 'Артас', 'country_code': 'GR'},
    {'code': 'PRE', 'name': 'Превеза', 'country_code': 'GR'},
    {'code': 'ARCA', 'name': 'Аркасиан', 'country_code': 'GR'},
    {'code': 'PYR', 'name': 'Пирей', 'country_code': 'GR'},
    {'code': 'MES', 'name': 'Мессиния', 'country_code': 'GR'},
    {'code': 'ARG', 'name': 'Арголида', 'country_code': 'GR'},
    {'code': 'COR', 'name': 'Коринф', 'country_code': 'GR'},
    {'code': 'SIF', 'name': 'Сифнос', 'country_code': 'GR'},
    {'code': 'KYT', 'name': 'Китеира', 'country_code': 'GR'},
    {'code': 'ANT', 'name': 'Антипарос', 'country_code': 'GR'},
    {'code': 'PAR', 'name': 'Парос', 'country_code': 'GR'},
    {'code': 'NAL', 'name': 'Наксос', 'country_code': 'GR'},
    {'code': 'AMI', 'name': 'Аморгос', 'country_code': 'GR'},
    {'code': 'IOS', 'name': 'Иос', 'country_code': 'GR'},
    {'code': 'SAN', 'name': 'Санторини', 'country_code': 'GR'},
    {'code': 'MYK', 'name': 'Миконос', 'country_code': 'GR'},
    {'code': 'TIN', 'name': 'Тинос', 'country_code': 'GR'},
    {'code': 'KEA', 'name': 'Кеа', 'country_code': 'GR'},
    {'code': 'SYR', 'name': 'Сирос', 'country_code': 'GR'},
    {'code': 'LER', 'name': 'Лернос', 'country_code': 'GR'},
    {'code': 'KOS', 'name': 'Кос', 'country_code': 'GR'},
    {'code': 'KAL', 'name': 'Калимнос', 'country_code': 'GR'},
    {'code': 'RHG', 'name': 'Родиас', 'country_code': 'GR'},
    {'code': 'KAR', 'name': 'Карпатос', 'country_code': 'GR'},
    {'code': 'AST', 'name': 'Асти', 'country_code': 'IT'},
    {'code': 'BAR', 'name': 'Бароло', 'country_code': 'IT'},
    {'code': 'BAR', 'name': 'Барбареско', 'country_code': 'IT'},
    {'code': 'GAJ', 'name': 'Гатиньола', 'country_code': 'IT'},
    {'code': 'SIN', 'name': 'Сингиола', 'country_code': 'IT'},
    {'code': 'BAS', 'name': 'Бароло-Сингиола', 'country_code': 'IT'},
    {'code': 'DIN', 'name': 'Динтроньер', 'country_code': 'FR'},
    {'code': 'BOU', 'name': 'Боузон', 'country_code': 'FR'},
    {'code': 'MEA', 'name': 'Меак', 'country_code': 'FR'},
    {'code': 'SAU', 'name': 'Сонье', 'country_code': 'FR'},
    {'code': 'VER', 'name': 'Версо', 'country_code': 'FR'},
    {'code': 'MEA', 'name': 'Меак-Шанон', 'country_code': 'FR'},
    {'code': 'JUL', 'name': 'Жюльен', 'country_code': 'FR'},
    {'code': 'BOU', 'name': 'Боузон-Шанон', 'country_code': 'FR'},
    {'code': 'CHA', 'name': 'Шатонеф-дю-Пап', 'country_code': 'FR'},
    {'code': 'CHT', 'name': 'Шатонеф-де-Гигондас', 'country_code': 'FR'},
    {'code': 'CHU', 'name': 'Шатонеф-де-Шоме', 'country_code': 'FR'},
    {'code': 'CHL', 'name': 'Шатонеф-де-Ла-Люн', 'country_code': 'FR'},
    {'code': 'CHV', 'name': 'Шатонеф-де-Виллер', 'country_code': 'FR'},
    {'code': 'CHC', 'name': 'Шатонеф-де-Коллин', 'country_code': 'FR'},
    {'code': 'CHP', 'name': 'Шатонеф-де-Поммероль', 'country_code': 'FR'},
    {'code': 'CHB', 'name': 'Шатонеф-де-Бордо', 'country_code': 'FR'},
    {'code': 'CHI', 'name': 'Шатонеф-де-Ирван', 'country_code': 'FR'},
    {'code': 'CHF', 'name': 'Шатонеф-де-Фуке', 'country_code': 'FR'},
    {'code': 'CHM', 'name': 'Шатонеф-де-Монперна', 'country_code': 'FR'},
    {'code': 'CHN', 'name': 'Шатонеф-де-Нарбон', 'country_code': 'FR'},
    {'code': 'CHO', 'name': 'Шатонеф-де-Оранж', 'country_code': 'FR'},
    {'code': 'CHG', 'name': 'Шатонеф-де-Гренобль', 'country_code': 'FR'},
    {'code': 'CHH', 'name': 'Шатонеф-де-Эр', 'country_code': 'FR'},
    {'code': 'CHX', 'name': 'Шатонеф-де-Ксеркс', 'country_code': 'FR'},
    {'code': 'CHY', 'name': 'Шатонеф-де-Йон', 'country_code': 'FR'},
    {'code': 'CHZ', 'name': 'Шатонеф-де-Зефир', 'country_code': 'FR'},
    {'code': 'CHAA', 'name': 'Шатонеф-де-Англез', 'country_code': 'FR'},
    {'code': 'CHBB', 'name': 'Шатонеф-де-Блуа', 'country_code': 'FR'},
    {'code': 'CHCC', 'name': 'Шатонеф-де-Шамбертен', 'country_code': 'FR'},
    {'code': 'CHDD', 'name': 'Шатонеф-де-Дижон', 'country_code': 'FR'},
    {'code': 'CHEE', 'name': 'Шатонеф-де-Эперней', 'country_code': 'FR'},
    {'code': 'CHFF', 'name': 'Шатонеф-де-Фалез', 'country_code': 'FR'},
    {'code': 'CHGG', 'name': 'Шатонеф-де-Гренад', 'country_code': 'FR'},
    {'code': 'CHHH', 'name': 'Шатонеф-де-Иль-де-Франс', 'country_code': 'FR'},
    {'code': 'CHII', 'name': 'Шатонеф-де-Изёр', 'country_code': 'FR'},
    {'code': 'CHJJ', 'name': 'Шатонеф-де-Жарден', 'country_code': 'FR'},
    {'code': 'CHKK', 'name': 'Шатонеф-де-Клермон-Ферран', 'country_code': 'FR'},
    {'code': 'CHLL', 'name': 'Шатонеф-де-Лион', 'country_code': 'FR'},
    {'code': 'CHMM', 'name': 'Шатонеф-де-Марсель', 'country_code': 'FR'},
    {'code': 'CHNN', 'name': 'Шатонеф-де-Ницца', 'country_code': 'FR'},
    {'code': 'CHOO', 'name': 'Шатонеф-де-Орлеан', 'country_code': 'FR'},
    {'code': 'CHPP', 'name': 'Шатонеф-де-Париж', 'country_code': 'FR'},
    {'code': 'CHQQ', 'name': 'Шатонеф-де-Квин', 'country_code': 'FR'},
    {'code': 'CHRR', 'name': 'Шатонеф-де-Реймс', 'country_code': 'FR'},
    {'code': 'CHSS', 'name': 'Шатонеф-де-Сен-Дени', 'country_code': 'FR'},
    {'code': 'CHTT', 'name': 'Шатонеф-де-Труа', 'country_code': 'FR'},
    {'code': 'CHUU', 'name': 'Шатонеф-де-Уазе', 'country_code': 'FR'},
    {'code': 'CHVV', 'name': 'Шатонеф-де-Версаль', 'country_code': 'FR'},
    {'code': 'CHWW', 'name': 'Шатонеф-де-Витри', 'country_code': 'FR'},
    {'code': 'CHXX', 'name': 'Шатонеф-де-Шарм', 'country_code': 'FR'},
    {'code': 'CHYY', 'name': 'Шатонеф-де-Йер', 'country_code': 'FR'},
    {'code': 'CHZZ', 'name': 'Шатонеф-де-Зуа', 'country_code': 'FR'},
    {'code': 'CHAAA', 'name': 'Шатонеф-де-Авиньон', 'country_code': 'FR'},
    {'code': 'CHBBB', 'name': 'Шатонеф-де-Безансон', 'country_code': 'FR'},
    {'code': 'CHCCC', 'name': 'Шатонеф-де-Шамберти', 'country_code': 'FR'},
    {'code': 'CHDDD', 'name': 'Шатонеф-де-Дижон-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHEEE', 'name': 'Шатонеф-де-Экс-ле-Бен', 'country_code': 'FR'},
    {'code': 'CHFFF', 'name': 'Шатонеф-де-Фонтенбло', 'country_code': 'FR'},
    {'code': 'CHGGG', 'name': 'Шатонеф-де-Гренобль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHHHH', 'name': 'Шатонеф-де-Иль-де-ла-Реюньон', 'country_code': 'FR'},
    {'code': 'CHIII', 'name': 'Шатонеф-де-Изёр-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHJJJ', 'name': 'Шатонеф-де-Жарден-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHKKK', 'name': 'Шатонеф-де-Клермон-Ферран-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHLLL', 'name': 'Шатонеф-де-Лион-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHMMM', 'name': 'Шатонеф-де-Марсель-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHNNN', 'name': 'Шатонеф-де-Ницца-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHOOO', 'name': 'Шатонеф-де-Орлеан-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHPPP', 'name': 'Шатонеф-де-Париж-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHQQQ', 'name': 'Шатонеф-де-Квин-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHRRR', 'name': 'Шатонеф-де-Реймс-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHSSS', 'name': 'Шатонеф-де-Сен-Дени-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHTTT', 'name': 'Шатонеф-де-Труа-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHUUU', 'name': 'Шатонеф-де-Уазе-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHVVV', 'name': 'Шатонеф-де-Версаль-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHWWW', 'name': 'Шатонеф-де-Витри-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHXXX', 'name': 'Шатонеф-де-Шарм-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHYYY', 'name': 'Шатонеф-де-Йер-ле-Вин', 'country_code': 'FR'},
    {'code': 'CHZZZ', 'name': 'Шатонеф-де-Зуа-ле-Вин', 'country_code': 'FR'},
  ];
  
  return ValueListenableBuilder<Map<String, dynamic>>(
    valueListenable: selectedFilters,
    builder: (context, filters, child) {
      // Получаем уже выбранные значения
      final selectedValues = (filters['region'] as List<String>?) ?? [];
      
      // Состояние для текста поиска
      final searchController = useTextEditingController();
      final filteredRegions = useState<List<Map<String, String>>>(allRegions);
      
      // Обработчик изменения текста поиска
      void onSearchTextChanged(String text) {
        if (text.isEmpty) {
          filteredRegions.value = allRegions;
        } else {
          filteredRegions.value = allRegions
              .where((region) => region['name']!.toLowerCase().contains(text.toLowerCase()))
              .toList();
        }
      }
      
      // Обновляем фильтрованный список при изменении начального значения
      useEffect(() {
        onSearchTextChanged(searchController.text);
        return null;
      }, []);
      
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          TextField(
            controller: searchController,
            decoration: const InputDecoration(
              labelText: 'Поиск по региону',
              prefixIcon: Icon(Icons.search),
            ),
            onChanged: (value) {
              onSearchTextChanged(value);
            },
          ),
          const SizedBox(height: 16),
          Expanded(
            child: ListView(
              children: [
                for (Map<String, String> region in filteredRegions.value)
                  CheckboxListTile(
                    title: Text(region['name']!),
                    value: selectedValues.contains(region['code']),
                    onChanged: (bool? value) {
                      final newSelectedValues = List<String>.from(selectedValues);
                      if (value == true) {
                        newSelectedValues.add(region['code']!);
                      } else {
                        newSelectedValues.remove(region['code']!);
                      }
                      selectedFilters.value['region'] = newSelectedValues;
                      selectedFilters.value = Map.from(selectedFilters.value);
                    },
                  ),
              ],
            ),
          ),
        ],
      );
    },
  );
}