// Mocks generated by Mockito 5.4.6 from annotations
// in winepool_final/test/features/wines/application/wine_label_search_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:winepool_final/features/wines/data/wines_repository.dart'
    as _i3;
import 'package:winepool_final/features/wines/domain/wine.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWine_0 extends _i1.SmartFake implements _i2.Wine {
  _FakeWine_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WinesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWinesRepository extends _i1.Mock implements _i3.WinesRepository {
  MockWinesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Wine>> fetchAllWines() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllWines, []),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<List<_i2.Wine>> fetchAllWinesNoFilter() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllWinesNoFilter, []),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<_i2.Wine> fetchWine(String? wineId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWine, [wineId]),
            returnValue: _i4.Future<_i2.Wine>.value(
              _FakeWine_0(this, Invocation.method(#fetchWine, [wineId])),
            ),
          )
          as _i4.Future<_i2.Wine>);

  @override
  _i4.Future<List<_i2.Wine>> fetchWinesByWinery(String? wineryId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWinesByWinery, [wineryId]),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<void> addWine(_i2.Wine? wine) =>
      (super.noSuchMethod(
            Invocation.method(#addWine, [wine]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateWine(_i2.Wine? wine) =>
      (super.noSuchMethod(
            Invocation.method(#updateWine, [wine]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteWine(String? wineId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWine, [wineId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Wine>> fetchPopularWines() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularWines, []),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<List<_i2.Wine>> fetchNewWines() =>
      (super.noSuchMethod(
            Invocation.method(#fetchNewWines, []),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<List<_i2.Wine>> searchWines(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchWines, [query]),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<List<_i2.Wine>> fetchWines(Map<String, dynamic>? filters) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWines, [filters]),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<Map<String, dynamic>> searchAll(
    String? query, [
    Set<String>? categories = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#searchAll, [query, categories]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
