// Mocks generated by Mockito 5.4.6 from annotations
// in winepool_final/test/features/wines/application/wine_label_search_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:winepool_final/features/wines/data/wines_repository.dart'
    as _i3;
import 'package:winepool_final/features/wines/domain/wine.dart' as _i2;
import 'package:winepool_final/features/wines/domain/wine_characteristics.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWine_0 extends _i1.SmartFake implements _i2.Wine {
  _FakeWine_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WinesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWinesRepository extends _i1.Mock implements _i3.WinesRepository {
  MockWinesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Wine>> fetchAllWines({bool? includeDeleted = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllWines, [], {
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<List<_i2.Wine>> fetchAllWinesNoFilter({
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllWinesNoFilter, [], {
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<_i2.Wine> fetchWine(String? wineId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWine, [wineId]),
            returnValue: _i4.Future<_i2.Wine>.value(
              _FakeWine_0(this, Invocation.method(#fetchWine, [wineId])),
            ),
          )
          as _i4.Future<_i2.Wine>);

  @override
  _i4.Future<List<_i2.Wine>> fetchWinesByWinery(
    String? wineryId, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchWinesByWinery,
              [wineryId],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<void> addWine(_i2.Wine? wine) =>
      (super.noSuchMethod(
            Invocation.method(#addWine, [wine]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateWine(_i2.Wine? wine) =>
      (super.noSuchMethod(
            Invocation.method(#updateWine, [wine]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteWine(String? wineId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWine, [wineId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Wine>> fetchPopularWines({
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularWines, [], {
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<List<_i2.Wine>> fetchNewWines({bool? includeDeleted = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNewWines, [], {
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<List<_i2.Wine>> searchWines(
    String? query, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchWines,
              [query],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<List<_i2.Wine>> fetchWinesWithFilters({
    List<_i5.WineColor>? color,
    List<_i5.WineType>? type,
    List<_i5.WineSugar>? sugar,
    double? minPrice,
    double? maxPrice,
    List<String>? country,
    List<String>? region,
    List<String>? grapeIds,
    List<String>? wineryIds,
    double? minRating,
    List<String>? bottleSizeIds,
    bool? showUnavailable = false,
    String? sortOption,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWinesWithFilters, [], {
              #color: color,
              #type: type,
              #sugar: sugar,
              #minPrice: minPrice,
              #maxPrice: maxPrice,
              #country: country,
              #region: region,
              #grapeIds: grapeIds,
              #wineryIds: wineryIds,
              #minRating: minRating,
              #bottleSizeIds: bottleSizeIds,
              #showUnavailable: showUnavailable,
              #sortOption: sortOption,
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i4.Future<List<_i2.Wine>>.value(<_i2.Wine>[]),
          )
          as _i4.Future<List<_i2.Wine>>);

  @override
  _i4.Future<Map<String, dynamic>> searchAll(
    String? query, [
    Set<String>? categories = const {},
    bool? includeDeleted = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#searchAll, [query, categories, includeDeleted]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> restoreWine(String? wineId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreWine, [wineId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
