import 'package:winepool_final/features/wines/domain/wine_characteristics.dart';

/// Класс для хранения извлеченных из текста данных о вине.
class WineLabelData {
  final String? name;
  final String? winery;
  final WineColor? color;
  final WineSugar? sugar;
  final double? alcoholLevel;
  // final String? grapeVariety; - убираем это поле из WineLabelData
  final int? vintage;
  // Добавляем дополнительные поля, которые могут быть полезны для поиска
  final List<String>? potentialNames;
  final List<String>? potentialWineries;
 final List<String>? potentialGrapes;

  const WineLabelData({
    this.name,
    this.winery,
    this.color,
    this.sugar,
    this.alcoholLevel,
    this.vintage,
    this.potentialNames,
    this.potentialWineries,
    this.potentialGrapes,
  });

  @override
  String toString() {
    return 'WineLabelData{name: $name, winery: $winery, color: $color, sugar: $sugar, alcoholLevel: $alcoholLevel, vintage: $vintage}';
  }
}

class WineLabelTextProcessor {
  // Словари для нормализации и сопоставления
  static const Map<String, String> _normalizationMap = {
    'вино': '',
    'красн.': 'красное',
    'бел.': 'белое',
    'роз.': 'розовое',
    'сух.': 'сухое',
    'сладк.': 'сладкое',
    'полусух.': 'полусухое',
    'полусладк.': 'полусладкое',
  };

  static const Set<String> _stopWords = {
    'алкоголь',
    'емкость',
    'мл',
    'l',
    'содержит',
    'продукт',
    'качество',
    'итого',
    'мужескаго',
    'пола',
    'на',
    'лицо',
    'vin',
    'vino',
    'wein',
    'wine',
    'produced',
    'by',
    'bottle',
    'bottled',
    'at',
    'the',
    'estate',
    'cellars',
    'cellar',
    'company',
    'co',
    'limited',
    'ltd',
    'inc',
    'corp',
    'corporation',
    'brewery',
    'distillery',
    'spirits',
    'beverages',
    'drink',
    'drinks',
    'alcoholic',
    'non',
    'alcohol',
    'abv',
    'alc',
    'volume',
    'contains',
    'sulphites',
    'sulfites',
    'allergens',
    'best',
    'before',
    'enjoy',
    'with',
    'food',
    'cheese',
    'meat',
    'fish',
    'pasta',
    'salad',
    'dessert',
    'aged',
    'oak',
    'barrel',
    'fermented',
    'filtered',
    'unfiltered',
    'organic',
    'bio',
    'natural',
    'premium',
    'quality',
    'fine',
    'reserve',
    'selection',
    'collection',
    'special',
    'edition',
    'anniversary',
    'gift',
    'pack',
    'set',
    'case',
    'box',
    'packaging',
    'label',
    'design',
    'trademark',
    'registered',
    'patent',
    'copyright',
    'rights',
    'reserved',
    'all',
    'copy',
    'right',
    'tm',
    '®',
    '©',
    '™',
    'pending',
    'application',
    'number',
    'serial',
    'no',
    'batch',
    'lot',
    'code',
    'date',
    'coded',
    'on',
    'packaged',
    'in',
    'for',
    'distributor',
    'importer',
    'exporter',
    'wholesaler',
    'retailer',
    'supplier',
    'manufacturer',
    'producer',
    'maker',
    'brand',
    'origin',
    'region',
    'country',
    'state',
    'province',
    'county',
    'city',
    'town',
    'village',
    'area',
    'zone',
    'district',
    'territory',
    'land',
    'soil',
    'climate',
    'weather',
    'sun',
    'rain',
    'snow',
    'temperature',
    'humidity',
    'wind',
    'air',
    'water',
    'earth',
    'nature',
    'environment',
    'eco',
    'green',
    'sustainable',
    'sustainability',
    'recyclable',
    'recycled',
    'plastic',
    'glass',
    'cork',
    'capsule',
    'closure',
    'cap',
    'lid',
    'top',
    'bottom',
    'side',
    'front',
    'back',
    'left',
    'up',
    'down',
    'high',
    'low',
    'middle',
    'center',
    'central',
    'main',
    'primary',
    'secondary',
    'tertiary',
    'first',
    'second',
    'third',
    'fourth',
    'fifth',
    'sixth',
    'seventh',
    'eighth',
    'ninth',
    'tenth',
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
    'eleven',
    'twelve',
    'thirteen',
    'fourteen',
    'fifteen',
    'sixteen',
    'seventeen',
    'eighteen',
    'nineteen',
    'twenty',
    'hundred',
    'thousand',
    'million',
    'billion',
    'trillion',
    'dozen',
    'pair',
    'group',
    'series',
    'range',
    'type',
    'kind',
    'sort',
    'style',
    'category',
    'classification',
    'grade',
    'level',
    'degree',
    'point',
    'mark',
    'score',
    'rating',
    'review',
    'comment',
    'feedback',
    'opinion',
    'thought',
    'idea',
    'concept',
    'theory',
    'practice',
    'method',
    'technique',
    'approach',
    'strategy',
    'plan',
    'goal',
    'objective',
    'target',
    'aim',
    'purpose',
    'intention',
    'meaning',
    'significance',
    'importance',
    'value',
    'worth',
    'benefit',
    'advantage',
    'disadvantage',
    'drawback',
    'limitation',
    'constraint',
    'restriction',
    'rule',
    'regulation',
    'law',
    'policy',
    'procedure',
    'protocol',
    'guideline',
    'standard',
    'specification',
    'requirement',
    'condition',
    'prerequisite',
    'precondition',
    'assumption',
    'hypothesis',
    'prediction',
    'forecast',
    'estimate',
    'calculation',
    'measurement',
    'size',
    'length',
    'width',
    'height',
    'depth',
    'thickness',
    'diameter',
    'radius',
    'circumference',
    'perimeter',
    'weight',
    'mass',
    'density',
    'pressure',
    'force',
    'energy',
    'power',
    'work',
    'heat',
    'light',
    'sound',
    'electricity',
    'magnetism',
    'gravity',
    'motion',
    'speed',
    'velocity',
    'acceleration',
    'time',
    'duration',
    'period',
    'interval',
    'frequency',
    'rate',
    'ratio',
    'proportion',
    'percentage',
    'fraction',
    'decimal',
    'integer',
    'digit',
    'figure',
    'amount',
    'quantity',
    'count',
    'total',
    'sum',
    'average',
    'mean',
    'median',
    'mode',
    'maximum',
    'minimum',
    'difference',
    'change',
    'variation',
    'deviation',
    'fluctuation',
    'shift',
    'transition',
    'transformation',
    'conversion',
    'modification',
    'adjustment',
    'correction',
    'revision',
    'update',
    'upgrade',
    'enhancement',
    'improvement',
    'optimization',
    'efficiency',
    'effectiveness',
    'performance',
    'capacity',
    'capability',
    'ability',
    'skill',
    'competence',
    'expertise',
    'knowledge',
    'information',
    'data',
    'facts',
    'figures',
    'statistics',
    'research',
    'study',
    'analysis',
    'evaluation',
    'assessment',
    'examination',
    'inspection',
    'testing',
    'experiment',
    'trial',
    'verification',
    'validation',
    'certification',
    'approval',
    'authorization',
    'permission',
    'license',
    'permit',
    'registration',
    'request',
    'demand',
    'need',
    'expectation',
    'hope',
    'wish',
    'desire',
    'want',
    'like',
    'love',
    'appreciate',
    'treasure',
    'cherish',
    'adore',
    'worship',
    'reverence',
    'respect',
    'admiration',
    'esteem',
    'honor',
    'glory',
    'fame',
    'renown',
    'reputation',
    'status',
    'position',
    'title',
    'identity',
    'character',
    'personality',
    'temperament',
    'mood',
    'feeling',
    'emotion',
    'sentiment',
    'passion',
    'excitement',
    'thrill',
    'adventure',
    'fun',
    'pleasure',
    'happiness',
    'joy',
    'delight',
    'satisfaction',
    'fulfillment',
    'contentment',
    'peace',
    'calm',
    'serenity',
    'tranquility',
    'quiet',
    'silence',
    'rest',
    'sleep',
    'dream',
    'vision',
    'imagination',
    'creativity',
    'innovation',
    'invention',
    'originality',
    'novelty',
    'uniqueness',
    'distinctiveness',
    'individuality',
    'trait',
    'feature',
    'aspect',
    'element',
    'component',
    'part',
    'section',
    'division',
    'segment',
    'unit',
    'module',
    'piece',
    'portion',
    'share',
    'allocation',
    'distribution',
    'assignment',
    'designation',
    'appointment',
    'nomination',
    'election',
    'choice',
    'decision',
    'judgment',
    'view',
    'perspective',
    'stance',
    'attitude',
    'behavior',
    'conduct',
    'action',
    'activity',
    'gesture',
    'expression',
    'communication',
    'speech',
    'talk',
    'conversation',
    'discussion',
    'dialogue',
    'debate',
    'argument',
    'dispute',
    'conflict',
    'struggle',
    'battle',
    'war',
    'harmony',
    'unity',
    'cooperation',
    'collaboration',
    'partnership',
    'teamwork',
    'friendship',
    'relationship',
    'bond',
    'connection',
    'link',
    'association',
    'affiliation',
    'membership',
    'belonging',
    'community',
    'society',
    'culture',
    'civilization',
    'history',
    'past',
    'present',
    'future',
    'yesterday',
    'today',
    'tomorrow',
    'morning',
    'afternoon',
    'evening',
    'night',
    'midnight',
    'noon',
    'dawn',
    'dusk',
    'day',
    'week',
    'month',
    'year',
    'decade',
    'century',
    'millennium',
    'era',
    'age',
    'epoch',
    'season',
    'spring',
    'summer',
    'autumn',
    'fall',
    'winter',
    'hot',
    'cold',
    'warm',
    'cool',
    'chilly',
    'frosty',
    'icy',
    'snowy',
    'rainy',
    'sunny',
    'cloudy',
    'stormy',
    'windy',
    'rough',
    'smooth',
    'soft',
    'hard',
    'strong',
    'weak',
    'powerful',
    'feeble',
    'mighty',
    'frail',
    'robust',
    'sturdy',
    'fragile',
    'delicate',
    'tender',
    'gentle',
    'harsh',
    'severe',
    'mild',
    'moderate',
    'extreme',
    'intense',
    'fierce',
    'violent',
    'peaceful',
    'still',
    'motionless',
    'static',
    'dynamic',
    'active',
    'inactive',
    'busy',
    'idle',
    'working',
    'resting',
    'playing',
    'studying',
    'teaching',
    'training',
    'education',
    'school',
    'college',
    'university',
    'academy',
    'institute',
    'library',
    'book',
    'reading',
    'writing',
    'literature',
    'poetry',
    'prose',
    'fiction',
    'non-fiction',
    'science',
    'mathematics',
    'physics',
    'chemistry',
    'biology',
    'geography',
    'philosophy',
    'psychology',
    'sociology',
    'economics',
    'politics',
    'government',
    'medicine',
    'health',
    'fitness',
    'sports',
    'games',
    'entertainment',
    'music',
    'art',
    'painting',
    'sculpture',
    'architecture',
    'photography',
    'cinema',
    'theater',
    'dance',
    'drama',
    'comedy',
    'tragedy',
    'romance',
    'mystery',
    'horror',
    'fantasy',
    'biography',
    'autobiography',
    'memoir',
    'journal',
    'diary',
    'letters',
    'emails',
    'messages',
    'communications',
    'technology',
    'computer',
    'internet',
    'software',
    'hardware',
    'network',
    'web',
    'digital',
    'analog',
    'electronic',
    'mechanical',
    'manual',
    'automatic',
    'robotic',
    'artificial',
    'intelligence',
    'ai',
    'machine',
    'learning',
    'deep',
    'neural',
    'algorithm',
    'programming',
    'coding',
    'development',
    'engineering',
    'construction',
    'building',
    'manufacturing',
    'production',
    'industry',
    'business',
    'commerce',
    'trade',
    'market',
    'economy',
    'finance',
    'banking',
    'investment',
    'stock',
    'currency',
    'money',
    'cash',
    'credit',
    'debt',
    'loan',
    'mortgage',
    'insurance',
    'risk',
    'profit',
    'loss',
    'revenue',
    'income',
    'expense',
    'price',
    'cost',
    'charge',
    'fee',
    'payment',
    'transaction',
    'sale',
    'purchase',
    'buy',
    'sell',
    'rent',
    'lease',
    'hire',
    'employment',
    'job',
    'career',
    'profession',
    'occupation',
    'labor',
    'service',
    'customer',
    'client',
    'consumer',
    'user',
    'buyer',
    'seller',
    'agent',
    'representative',
    'spokesman',
    'spokeswoman',
    'spokesperson',
    'mediator',
    'negotiator',
    'diplomat',
    'ambassador',
    'envoy',
    'delegate',
    'official',
    'authority',
    'leader',
    'chief',
    'head',
    'boss',
    'manager',
    'supervisor',
    'director',
    'president',
    'ceo',
    'executive',
    'administrator',
    'coordinator',
    'organizer',
    'planner',
    'strategist',
    'advisor',
    'consultant',
    'analyst',
    'researcher',
    'scientist',
    'engineer',
    'technician',
    'specialist',
    'expert',
    'professional',
    'skilled',
    'trained',
    'qualified',
    'certified',
    'licensed',
    'authorized',
    'approved',
    'accepted',
    'recognized',
    'respected',
    'trusted',
    'reliable',
    'dependable',
    'responsible',
    'accountable',
    'honest',
    'truthful',
    'sincere',
    'genuine',
    'authentic',
    'real',
    'actual',
    'true',
    'factual',
    'accurate',
    'precise',
    'exact',
    'correct',
    'proper',
    'appropriate',
    'suitable',
    'fitting',
    'adequate',
    'sufficient',
    'enough',
    'ample',
    'abundant',
    'plentiful',
    'rich',
    'wealthy',
    'prosperous',
    'successful',
    'fortunate',
    'lucky',
    'blessed',
    'privileged',
    'happy',
    'content',
    'satisfied',
    'grateful',
    'thankful',
    'appreciative',
    'obliged',
    'indebted',
    'owed',
    'due',
    'payable',
    'collectible',
    'recoverable',
    'refundable',
    'returnable',
    'exchangeable',
    'transferable',
    'movable',
    'portable',
    'mobile',
    'transportable',
    'shippable',
    'deliverable',
    'reachable',
    'accessible',
    'available',
    'ready',
    'prepared',
    'equipped',
    'furnished',
    'supplied',
    'provided',
    'offered',
    'presented',
    'delivered',
    'distributed',
    'shared',
    'allocated',
    'assigned',
    'designated',
    'appointed',
    'named',
    'called',
    'titled',
    'labeled',
    'tagged',
    'marked',
    'identified',
    'classified',
    'categorized',
    'grouped',
    'organized',
    'arranged',
    'sorted',
    'ordered',
    'sequenced',
    'ranked',
    'graded',
    'evaluated',
    'assessed',
    'measured',
    'quantified',
    'calculated',
    'computed',
    'estimated',
    'predicted',
    'projected',
    'forecasted',
    'anticipated',
    'expected',
    'awaited',
    'desired',
    'wanted',
    'needed',
    'required',
    'demanded',
    'asked',
    'sought',
    'searched',
    'looked',
    'hunted',
    'tracked',
    'followed',
    'pursued',
    'chased',
    'found',
    'discovered',
    'located',
    'detected',
    'noticed',
    'observed',
    'seen',
    'watched',
    'monitored',
    'supervised',
    'controlled',
    'managed',
    'handled',
    'operated',
    'used',
    'employed',
    'utilized',
    'applied',
    'implemented',
    'executed',
    'carried',
    'out',
    'performed',
    'accomplished',
    'achieved',
    'completed',
    'finished',
    'ended',
    'terminated',
    'concluded',
    'closed',
    'ceased',
    'stopped',
    'halted',
    'paused',
    'interrupted',
    'delayed',
    'postponed',
    'rescheduled',
    'cancelled',
    'abandoned',
    'given',
    'quit',
    'retired',
    'withdrawn',
    'removed',
    'deleted',
    'erased',
    'eliminated',
    'exterminated',
    'destroyed',
    'ruined',
    'damaged',
    'broken',
    'defective',
    'faulty',
    'malfunctioning',
    'order',
    'inoperative',
    'useless',
    'worthless',
    'valueless',
    'helpless',
    'powerless',
    'ineffective',
    'inefficient',
    'unproductive',
    'fruitless',
    'vain',
    'futile',
    'pointless',
    'meaningless',
    'senseless',
    'absurd',
    'ridiculous',
    'illogical',
    'irrational',
    'unreasonable',
    'impractical',
    'impossible',
    'unfeasible',
    'unrealistic',
    'overly',
    'optimistic',
    'pessimistic',
    'negative',
    'positive',
    'neutral',
    'balanced',
    'fair',
    'just',
    'equitable',
    'equal',
    'same',
    'identical',
    'similar',
    'alike',
    'comparable',
    'parallel',
    'equivalent',
    'corresponding',
    'matching',
    'consistent',
    'compatible',
    'harmonious',
    'concordant',
    'agreeable',
    'pleasant',
    'likable',
    'attractive',
    'appealing',
    'charming',
    'lovely',
    'beautiful',
    'pretty',
    'handsome',
    'gorgeous',
    'stunning',
    'magnificent',
    'splendid',
    'grand',
    'impressive',
    'remarkable',
    'extraordinary',
    'exceptional',
    'outstanding',
    'prominent',
    'distinguished',
    'notable',
    'famous',
    'celebrated',
    'renowned',
    'well-known',
    'popular',
    'common',
    'usual',
    'typical',
    'normal',
    'regular',
    'conventional',
    'traditional',
    'orthodox',
    'conservative',
    'progressive',
    'liberal',
    'radical',
    'revolutionary',
    'innovative',
    'modern',
    'contemporary',
    'current',
    'recent',
    'late',
    'new',
    'fresh',
    'novel',
    'original',
    'creative',
    'imaginative',
    'inventive',
    'resourceful',
    'clever',
    'smart',
    'intelligent',
    'bright',
    'sharp',
    'keen',
    'astute',
    'perceptive',
    'insightful',
    'wise',
    'sensible',
    'prudent',
    'cautious',
    'careful',
    'attentive',
    'alert',
    'vigilant',
    'watchful',
    'observant',
    'aware',
    'conscious',
    'mindful',
    'considerate',
    'thoughtful',
    'reflective',
    'meditative',
    'contemplative',
    'philosophical',
    'abstract',
    'theoretical',
    'practical',
    'empirical',
    'experimental',
    'observational',
    'analytical',
    'critical',
    'skeptical',
    'doubtful',
    'uncertain',
    'unsure',
    'hesitant',
    'reluctant',
    'willing',
    'disposed',
    'inclined',
    'apt',
    'likely',
    'probable',
    'possible',
    'potential',
    'feasible',
    'achievable',
    'realizable',
    'attainable',
    'obtainable',
    'acquirable',
    'secure',
    'stable',
    'steady',
    'firm',
    'solid',
    'resilient',
    'flexible',
    'adaptable',
    'versatile',
    'diverse',
    'varied',
    'multiple',
    'numerous',
    'many',
    'several',
    'various',
    'different',
    'distinct',
    'separate',
    'individual',
    'private',
    'personal',
    'intimate',
    'close',
    'near',
    'adjacent',
    'proximate',
    'remote',
    'distant',
    'far',
    'away',
    'absent',
    'missing',
    'lost',
    'misplaced',
    'forgotten',
    'remembered',
    'recalled',
    'reminded',
    'awakened',
    'aroused',
    'stimulated',
    'activated',
    'triggered',
    'initiated',
    'started',
    'launched',
    'begun',
    'commenced',
    'inaugurated',
    'inaugural',
    'opening',
    'initial',
    'principal',
    'leading',
    'foremost',
    'major',
    'significant',
    'important',
    'crucial',
    'vital',
    'essential',
    'indispensable',
    'necessary',
    'mandatory',
    'compulsory',
    'obligatory',
    'binding',
    'legal',
    'lawful',
    'legitimate',
    'valid',
    'effective',
    'operative',
    'functional',
    'efficient',
    'productive',
    'profitable',
    'gainful',
    'remunerative',
    'lucrative',
    'rewarding',
    'satisfying',
    'fulfilling',
    'meaningful',
    'purposeful',
    'worthwhile',
    'valuable',
    'beneficial',
    'advantageous',
    'helpful',
    'supportive',
    'constructive',
    'destructive',
    'detrimental',
    'harmful',
    'injurious',
    'noxious',
    'toxic',
    'poisonous',
    'deadly',
    'fatal',
    'lethal',
    'mortal',
    'terminal',
    'final',
    'ultimate',
    'last',
    'ending',
    'concluding',
    'closing',
    'terminating',
    'finishing',
    'completing',
    'accomplishing',
    'achieving',
    'reaching',
    'attaining',
    'gaining',
    'obtaining',
    'securing',
    'acquiring',
    'procuring',
    'fetching',
    'bringing',
    'carrying',
    'transporting',
    'moving',
    'shifting',
    'transferring',
    'passing',
    'handing',
    'giving',
    'offering',
    'presenting',
    'donating',
    'contributing',
    'sharing',
    'distributing',
    'allocating',
    'assigning',
    'allotting',
    'awarding',
    'granting',
    'bestowing',
    'conferring',
    'imparting',
  };

  static const Set<String> _colorKeywords = {
    'красное',
    'белое',
    'розовое',
    'red',
    'white',
    'rose',
    'rosé',
  };

  static const Set<String> _sugarKeywords = {
    'сухое',
    'полусухое',
    'полусладкое',
    'сладкое',
    'брют',
    'dry',
    'semi-dry',
    'semi-sweet',
    'sweet',
    'brut',
  };

  /// Обрабатывает текст с этикетки вина и извлекает сущности.
  ///
  /// Возвращает объект [WineLabelData] с извлеченными полями.
  /// Поля могут быть null, если соответствующая информация не найдена.
  WineLabelData processText(String rawText) {
    if (rawText.trim().isEmpty) {
      return const WineLabelData();
    }
    // 1.1. Извлечение имени в кавычках из оригинального текста для сохранения регистра
    String? nameInQuotes = _extractNameInQuotes(rawText);
    
    // 1.2. Предварительная обработка текста (приведение к нижнему регистру, нормализация, удаление стоп-слов)
    final cleanedText = _preprocessText(rawText);
    
    // 1.3. Извлечение остальных сущностей из обработанного текста
    final extractedEntities = _extractEntities(cleanedText, rawText, nameInQuotes);
    
    return WineLabelData(
      name: extractedEntities.name,
      winery: extractedEntities.winery,
      color: extractedEntities.color,
      sugar: extractedEntities.sugar,
      alcoholLevel: extractedEntities.alcoholLevel,
      // grapeVariety больше не используется в Wine и не передается
      vintage: extractedEntities.vintage,
      potentialNames: extractedEntities.potentialNames,
      potentialWineries: extractedEntities.potentialWineries,
      potentialGrapes: extractedEntities.potentialGrapes,
    );
  }

  /// Выполняет предварительную обработку текста.
  String _preprocessText(String rawText) {
    var processed = rawText.toLowerCase();
    
    // Удаление кавычек после того, как мы попытались извлечь из них имя
    processed = processed.replaceAll(RegExp(r'["«»]'), '');
    
    // Удаление прочих лишних символов
    processed = processed.replaceAll(RegExp(r'[*_]'), '');
    
    // Нормализация
    for (final entry in _normalizationMap.entries) {
      processed = processed.replaceAll(entry.key, entry.value);
    }
    
    // Удаление стоп-слов
    final words = processed.split(RegExp(r'\s+'));
    final filteredWords = words.where((word) => !_stopWords.contains(word.trim())).toList();
    processed = filteredWords.join(' ');
    
    // Удаление лишних пробелов
    processed = processed.trim().replaceAll(RegExp(r'\s+'), ' ');
    
    return processed;
 }

  String? _extractNameInQuotes(String rawText) {
    final quoteMatch = RegExp(r'["«]([^"»]+)["»]').firstMatch(rawText);
    if (quoteMatch != null && quoteMatch.group(1) != null) {
      final potentialName = quoteMatch.group(1)!.trim();
      if (int.tryParse(potentialName) == null) {
        return potentialName;
      }
    }
    return null;
  }

  /// Извлекает сущности из предварительно обработанного текста.
  _ExtractedEntities _extractEntities(String cleanedText, String rawText, String? nameInQuotes) {
    // В реальной реализации мы бы получили эти списки из базы данных
    final knownNames = <String>['chateau margaux'];
    final knownWineries = <String>[];
    final knownGrapes = <String>['каберне совиньон', 'chardonnay'];
    
    String? name = nameInQuotes ?? _extractKnownEntity(cleanedText, knownNames);
    String? winery = _extractKnownEntity(cleanedText, knownWineries);
    WineColor? color = _extractColor(cleanedText);
    WineSugar? sugar = _extractSugar(cleanedText);
    double? alcoholLevel = _extractAlcoholLevel(cleanedText);
    // String? grapeVariety = _extractGrapeVariety(cleanedText) ?? _extractKnownEntity(cleanedText, knownGrapes); // Больше не используется
    int? vintage = _extractVintage(cleanedText);
    
    // Также извлекаем потенциальные совпадения для дальнейшего поиска
    final potentialNames = _findPotentialMatches(cleanedText, knownNames);
    final potentialWineries = _findPotentialMatches(cleanedText, knownWineries);
    final potentialGrapes = _findPotentialMatches(cleanedText, knownGrapes);
    
    return _ExtractedEntities(
      name: name,
      winery: winery,
      color: color,
      sugar: sugar,
      alcoholLevel: alcoholLevel,
      // grapeVariety больше не используется в Wine и не передается
      vintage: vintage,
      potentialNames: potentialNames,
      potentialWineries: potentialWineries,
      potentialGrapes: potentialGrapes,
    );
  }

  String? _extractKnownEntity(String text, List<String> knownEntities) {
    for (final entity in knownEntities) {
      if (text.contains(entity.toLowerCase())) {
        return entity;
      }
    }
    return null;
  }

  WineColor? _extractColor(String text) {
    for (final keyword in _colorKeywords) {
      if (text.contains(keyword)) {
        switch (keyword) {
          case 'красное':
          case 'red':
            return WineColor.red;
          case 'белое':
          case 'white':
            return WineColor.white;
          case 'розовое':
          case 'rose':
          case 'rosé':
            return WineColor.rose;
        }
      }
    }
    return null;
  }

  WineSugar? _extractSugar(String text) {
    for (final keyword in _sugarKeywords) {
      if (text.contains(keyword)) {
        switch (keyword) {
          case 'сухое':
          case 'dry':
            return WineSugar.dry;
          case 'полусухое':
          case 'semi-dry':
            return WineSugar.semiDry;
          case 'полусладкое':
          case 'semi-sweet':
            return WineSugar.semiSweet;
          case 'сладкое':
          case 'sweet':
            return WineSugar.sweet;
          case 'брют':
          case 'brut':
            // Брут - это обычно про игристые вина, но можно отнести к сухим
            return WineSugar.dry;
        }
      }
    }
    return null;
  }

  double? _extractAlcoholLevel(String text) {
    final alcoholMatch = RegExp(r'(\d{1,2}\.\d|\d{1,2})\s*%').firstMatch(text);
    if (alcoholMatch != null) {
      final alcoholStr = alcoholMatch.group(1);
      return double.tryParse(alcoholStr!);
    }
    return null;
  }

  String? _extractGrapeVariety(String text) {
    final grapeMatch = RegExp(r'(?:сор[т]\sвинограда|grape\svariety:?)\s+([a-zA-Zа-яё\s\-]+?)(?=\s\d{4}|\s|,|$)')
        .firstMatch(text);
    if (grapeMatch != null) {
      return grapeMatch.group(1)?.trim();
    }
    return null;
  }

  int? _extractVintage(String text) {
    // Ищем 4-значное число, возможно, после "винтаж", "vintage", "année", "millésime".
    final vintageMatch = RegExp(r'(?:винтаж|vintage|année|millésime|\.|\s)\s*(\d{4})', caseSensitive: false)
        .firstMatch(text);
    if (vintageMatch != null) {
      final yearStr = vintageMatch.group(1);
      final year = int.tryParse(yearStr!);
      // Проверяем, что год в разумном диапазоне (например, между 1900 и текущим годом + 1).
      if (year != null && year >= 1900 && year <= DateTime.now().year + 1) {
        return year;
      }
    }
    
    // Если не найдено по ключевым словам, ищем любое 4-значное число в диапазоне
    final allNumbers = RegExp(r'\b(19\d{2}|20\d{2})\b')
        .allMatches(text)
        .map((match) => int.tryParse(match.group(0)!))
        .where((year) => year != null && year >= 1900 && year <= DateTime.now().year + 1)
        .toList();
        
    if (allNumbers.isNotEmpty) {
      // Возвращаем наибольший найденный год (предполагаем, что это самый актуальный)
      return allNumbers.whereType<int>().reduce((a, b) => a > b ? a : b);
    }
    
    return null;
 }

 /// Находит потенциальные совпадения с известными значениями
 List<String>? _findPotentialMatches(String text, List<String> knownValues) {
    final matches = <String>[];
    for (final value in knownValues) {
      if (text.contains(value.toLowerCase())) {
        matches.add(value);
      }
    }
    return matches.isNotEmpty ? matches : null;
  }
}

/// Вспомогательный класс для внутреннего использования
class _ExtractedEntities {
  final String? name;
  final String? winery;
  final WineColor? color;
  final WineSugar? sugar;
 final double? alcoholLevel;
  // final String? grapeVariety; - убираем это поле
  final int? vintage;
  final List<String>? potentialNames;
  final List<String>? potentialWineries;
  final List<String>? potentialGrapes;

  _ExtractedEntities({
    this.name,
    this.winery,
    this.color,
    this.sugar,
    this.alcoholLevel,
    this.vintage,
    this.potentialNames,
    this.potentialWineries,
    this.potentialGrapes,
  });
}
